<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260728120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial WB bidder schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE campaigns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, wb_advert_id INT NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, level1_enabled BOOLEAN NOT NULL, target_roas NUMERIC(10, 4) NOT NULL, metrics_window_days INT NOT NULL, restrict_up_if_roas_below NUMERIC(10, 4) NOT NULL, allow_up_if_roas_above NUMERIC(10, 4) NOT NULL, level2_enabled BOOLEAN NOT NULL, target_cpa NUMERIC(12, 2) NOT NULL, cpa_buffer NUMERIC(12, 2) NOT NULL, pause_if_cpa_above NUMERIC(12, 2) DEFAULT NULL, min_orders INT NOT NULL, min_impressions INT NOT NULL, min_bid_kopecks INT NOT NULL, max_bid_kopecks INT NOT NULL, max_change_up_pct INT NOT NULL, max_change_down_pct INT NOT NULL, growth_max_change_up_pct INT NOT NULL, cooldown_hours INT NOT NULL, dry_run BOOLEAN NOT NULL, bidding_enabled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_campaign_wb_id ON campaigns (wb_advert_id)');

        $this->addSql('CREATE TABLE clusters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, campaign_id INT NOT NULL, nm_id INT NOT NULL, norm_query VARCHAR(500) NOT NULL, current_bid_kopecks INT NOT NULL, paused BOOLEAN NOT NULL, last_bid_change_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_campaign_norm_query ON clusters (campaign_id, norm_query)');
        $this->addSql('CREATE INDEX IDX_cluster_campaign ON clusters (campaign_id)');
        $this->addSql('ALTER TABLE clusters ADD CONSTRAINT FK_cluster_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE campaign_daily_stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, campaign_id INT NOT NULL, date DATE NOT NULL, views INT NOT NULL, clicks INT NOT NULL, orders INT NOT NULL, spend NUMERIC(14, 2) NOT NULL, revenue NUMERIC(14, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_campaign_date ON campaign_daily_stats (campaign_id, date)');
        $this->addSql('ALTER TABLE campaign_daily_stats ADD CONSTRAINT FK_campaign_stat FOREIGN KEY (campaign_id) REFERENCES campaigns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE cluster_daily_stats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cluster_id INT NOT NULL, date DATE NOT NULL, views INT NOT NULL, clicks INT NOT NULL, orders INT NOT NULL, spend NUMERIC(14, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cluster_date ON cluster_daily_stats (cluster_id, date)');
        $this->addSql('ALTER TABLE cluster_daily_stats ADD CONSTRAINT FK_cluster_stat FOREIGN KEY (cluster_id) REFERENCES clusters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE bid_decisions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, campaign_id INT NOT NULL, cluster_id INT NOT NULL, campaign_mode VARCHAR(255) DEFAULT NULL, proposal_action VARCHAR(255) DEFAULT NULL, final_action VARCHAR(255) NOT NULL, old_bid_kopecks INT NOT NULL, new_bid_kopecks INT NOT NULL, reason TEXT NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE bid_decisions ADD CONSTRAINT FK_decision_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bid_decisions ADD CONSTRAINT FK_decision_cluster FOREIGN KEY (cluster_id) REFERENCES clusters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE bid_decisions DROP CONSTRAINT FK_decision_campaign');
        $this->addSql('ALTER TABLE bid_decisions DROP CONSTRAINT FK_decision_cluster');
        $this->addSql('DROP TABLE bid_decisions');
        $this->addSql('ALTER TABLE cluster_daily_stats DROP CONSTRAINT FK_cluster_stat');
        $this->addSql('DROP TABLE cluster_daily_stats');
        $this->addSql('ALTER TABLE campaign_daily_stats DROP CONSTRAINT FK_campaign_stat');
        $this->addSql('DROP TABLE campaign_daily_stats');
        $this->addSql('ALTER TABLE clusters DROP CONSTRAINT FK_cluster_campaign');
        $this->addSql('DROP TABLE clusters');
        $this->addSql('DROP TABLE campaigns');
    }
}
